language: ruby
rvm:
- 2.4
- 2.5
- 2.6
script:
- bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: LKpYdRJImFZgpZ8NP5jah0pWUUwlmrXIW+dCfyFitm4Xf91XkZ3n4/g1WaUoZwmb/9FAian7PR/3XPuiNSEitr3J8DdbJMH9A/CG3VSyIgj/NE9w5Zl/mC6Pz8F0Ry7iSQ3kjhiW74927vRxc6VenHkm/oaBOwz3NfZQCoIEo27rDW1Xu+K4RviPL76k53Pm06C3xupibQ2m2+OKqwW8QlPCfcN1Q4Vkv/gokXjxGlxBYxxvEfZzCc3ul6TZTWeJgkSsfha6/MjHUj2q40sY+m4MMOrgdWGqau9xayJSQuDdP8c0C6hSyL2arHwbPDSO/4hsm0/h0Alfwrmm4sQmPcI2gVowL7yM44vTtTnuigRKhOFhgaNJH+mNTCGtAxH9Ke5Vx0ZjRKpWAXeE1Js1WARNX5gNj5jhZeyeQn5USV/YLJSqiB188Y0lnt3qdLc7h5FJlXWGgKf3+EPnnPupLaSkL9VWdMCVcP1hlp2CUhJo7dBKANzPiUP+sAsSuA3Ez681OOXPjRTfXFhfBSCd7XBnkvw/iZQeIiiZNbh/3CTKQ0tkJIwnnLR4qKsty3KZHH2cqxYfQkaSjmKDeHymQywWqPO9rUL6oxUz2chkLeiv9iEk/t8pTp+RBRx2K1fVB7/tZ1Ys+eGZBdS1lIrRmvvcVE0g6mAfcwhhyJHuPsk=
  on:
    tags: true
